version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-location-api
    ports:
      - "8080:8080"
    environment:
      - POSITION_STACK_API_KEY=${POSITION_STACK_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pet-location-network

networks:
  pet-location-network:
    driver: bridge
